group_keywords = {
    'Group 1': ['pop', 'dance', 'disco', 'upbeat', 'catchy'],
    'Group 2': ['rock', 'alternative', 'classic', 'indie', 'punk', 'grunge'],
    'Group 3': ['hip-hop', 'rap', 'trap', 'urban', 'beats'],
    'Group 4': ['jazz', 'smooth', 'swing', 'bebop', 'improvisation'],
    'Group 5': ['electronic', 'edm', 'techno', 'house', 'trance', 'ambient', 'synth'],
    'Group 6': ['country', 'western', 'folk', 'americana'],
    'Group 7': ['r&b', 'soul', 'rhythm', 'blues', 'neo-soul', 'motown'],
    'Group 8': ['classical', 'symphony', 'orchestral', 'baroque', 'opera'],
    'Group 9': ['alternative', 'indie', 'experimental', 'offbeat'],
    'Group 10': ['indie', 'independent', 'underground', 'lo-fi'],
    'Group 11': ['reggae', 'ska', 'dub', 'dancehall', 'caribbean'],
    'Group 12': ['metal', 'heavy', 'thrash', 'death', 'black'],
    'Group 13': ['folk', 'traditional', 'acoustic', 'roots', 'singer-songwriter'],
    'Group 14': ['funk', 'groove', 'soul', 'r&b', 'dance'],
    'Group 15': ['blues', 'delta', 'chicago', 'electric'],
    'Group 16': ['dance', 'electronic', 'club', 'party', 'upbeat'],
    'Group 17': ['latin', 'salsa', 'merengue', 'bachata', 'reggaeton'],
    'Group 18': ['world', 'global', 'ethnic', 'traditional'],
    'Group 19': ['punk', 'garage', 'energetic', 'rebellious'],
    'Group 20': ['experimental', 'avant-garde', 'abstract', 'unconventional']
}

group_personality_mapping = {
    'Group 1': ['Energetic', 'Outgoing', 'Upbeat', 'Vibrant'],
    'Group 2': ['Rebellious', 'Passionate', 'Edgy', 'Fiery'],
    'Group 3': ['Confident', 'Bold', 'Dynamic', 'Charismatic'],
    'Group 4': ['Sophisticated', 'Artistic', 'Cultured', 'Creative'],
    'Group 5': ['Innovative', 'Eccentric', 'Imaginative', 'Experimental'],
    'Group 6': ['Down-to-earth', 'Relaxed', 'Chill', 'Easygoing'],
    'Group 7': ['Soulful', 'Emotional', 'Expressive', 'Heartfelt'],
    'Group 8': ['Intellectual', 'Poetic', 'Thoughtful', 'Reflective'],
    'Group 9': ['Alternative', 'Quirky', 'Unique', 'Offbeat'],
    'Group 10': ['Independent', 'Introspective', 'Thought-provoking', 'Contemplative'],
    'Group 11': ['Laid-back', 'Cheerful', 'Happy', 'Optimistic'],
    'Group 12': ['Aggressive', 'Powerful', 'Intense', 'Dominant'],
    'Group 13': ['Rooted', 'Authentic', 'Genuine', 'Honest'],
    'Group 14': ['Groovy', 'Funky', 'Soulful', 'Rhythmic'],
    'Group 15': ['Bluesy', 'Expressive', 'Melancholic', 'Soul-stirring'],
    'Group 16': ['Upbeat', 'High-energy', 'Energetic', 'Dynamic'],
    'Group 17': ['Passionate', 'Sensual', 'Romantic', 'Seductive'],
    'Group 18': ['Diverse', 'Cultural', 'Exotic', 'Worldly'],
    'Group 19': ['Edgy', 'Energetic', 'Rebellious', 'Unconventional'],
    'Group 20': ['Avant-garde', 'Unconventional', 'Innovative', 'Boundary-pushing']
}

personality_values = {
    'Energetic': 5,
    'Outgoing': 4,
    'Upbeat': 3,
    'Vibrant': 5,
    'Rebellious': 4,
    'Passionate': 3,
    'Edgy': 4,
    'Fiery': 5,
    'Confident': 4,
    'Bold': 3,
    'Dynamic': 4,
    'Charismatic': 5,
    'Sophisticated': 3,
    'Artistic': 4,
    'Cultured': 3,
    'Creative': 4,
    'Innovative': 5,
    'Eccentric': 4,
    'Imaginative': 3,
    'Experimental': 4,
    'Down-to-earth': 3,
    'Relaxed': 4,
    'Chill': 3,
    'Easygoing': 4,
    'Soulful': 5,
    'Emotional': 4,
    'Expressive': 3,
    'Heartfelt': 4,
    'Intellectual': 5,
    'Poetic': 4,
    'Thoughtful': 3,
    'Reflective': 4,
    'Alternative': 3,
    'Quirky': 4,
    'Unique': 3,
    'Offbeat': 4,
    'Independent': 5,
    'Introspective': 4,
    'Thought-provoking': 3,
    'Contemplative': 4,
    'Laid-back': 3,
    'Cheerful': 4,
    'Happy': 3,
    'Optimistic': 4,
    'Aggressive': 5,
    'Powerful': 4,
    'Intense': 3,
    'Dominant': 4,
    'Rooted': 5,
    'Authentic': 4,
    'Genuine': 3,
    'Honest': 4,
    'Groovy': 5,
    'Funky': 4,
    'Rhythmic': 3,
    'Bluesy': 4,
    'Melancholic': 5,
    'Soul-stirring': 4,
    'Passionate': 3,
    'Sensual': 4,
    'Romantic': 3,
    'Seductive': 4,
    'Diverse': 5,
    'Cultural': 4,
    'Exotic': 3,
    'Worldly': 4,
    'Edgy': 5,
    'Unconventional': 4,
    'Innovative': 3,
    'Boundary-pushing': 4,
}

color_mapping = {
    (1, 1.75): '#ADD8E6',  # Light Blue
    (1.75, 2.5): '#AFEEEE',  # Pale Turquoise
    (2.5, 3.25): '#90EE90',  # Soft Green
    (3.25, 4): '#32CD32',  # Light Lime
    (4, 4.75): '#FFFF99',  # Pale Yellow
    (4.75, 5.5): '#FFDAB9',  # Peach
    (5.5, 6.25): '#F08080',  # Light Coral
    (6.25, 7): '#FFC0CB'  # Soft Pink
}


